server:
  port: 8080
  servlet:
    context-path: /friend-hub

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/YOUR_DATABASE
    username: USER_USERNAME
    password: YOUR_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL
    password: YOUR_APP_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  frontend-url: http://localhost:5173
  reset-password:
    expire-minutes: 15

jwt:
  signerKey: "qefqi5X+n/6jIHV74cPC6QTZvKBmyddMNhw7vWO3Yu7Rk1YdN2EWNjs7zJX/ZL0i"
  validDuration: 3600
  refreshableDuration: 86400

upload-file:
  base-uri: YOUR_FOLDER_PATH
