server:
  port: 8080
  servlet:
    context-path: /friend-hub

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  signerKey: "qefqi5X+n/6jIHV74cPC6QTZvKBmyddMNhw7vWO3Yu7Rk1YdN2EWNjs7zJX/ZL0i"
  validDuration: 86400
  refreshableDuration: 86400

upload-file:
  base-uri: YOUR_FILE_PATH
